# See https://www.mediawiki.org/wiki/Manual:Coding_conventions/Ruby

AllCops:
  StyleGuideCopsOnly: true

Metrics/MethodLength:
  Enabled: false

Style/Alias:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/TrivialAccessors:
  ExactNameMatch: true

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/AsciiComments:
  Enabled: false

Metrics/LineLength:
  Max: 130
